import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties, type KeyboardEvent, type MouseEvent } from "react";
import { invoke } from "@tauri-apps/api/core";
import { openUrl } from "@tauri-apps/plugin-opener";
import { type CatalogEntry, type CatalogResponse } from "./catalog";
import "./styles.css";

const catalogs = ["Artifacts", "Cards", "Consumables", "Gems", "Maps", "Materials", "Monsters", "Equipment", "Skills"];
const cardSlots = ["Accessory", "Chest", "Face", "Headgear", "Legwear", "Shield", "Shoes", "Utility", "Weapon"];
const resolutions = [[960, 540, "Compact"], [1280, 720, "Standard"], [1600, 900, "Wide"], [1920, 1080, "Full HD"]] as const;
const normalize = (value: string) => value.toLowerCase().trim();
const catalogClass = (kind: string) => `catalog-${normalize(kind).replace(/[^a-z0-9]+/g, "-")}`;
const taggedType = (entry: CatalogEntry, fallback: "Normal" | "Skill") => entry.tags.find((tag) => tag === "Boss" || tag === "Normal" || tag === "Skill") ?? fallback;
const catalogColors: Record<string, string> = { Artifacts: "#f4bd8d", Cards: "#b8a5ff", Consumables: "#ff9fbe", Gems: "#71d8e8", Maps: "#efda72", Materials: "#c9b096", Monsters: "#f58d84", Equipment: "#89c5ff", Skills: "#b6e96b" };

type Theme = { label: string; background: string; surface: string; accent: string; stripe: [string, string, string] };
type SearchResult = { entry: CatalogEntry; score: number; reason: string };
type LinkCandidate = { key: string; entry: CatalogEntry };
type LinkMatch = { entry: CatalogEntry; start: number; length: number };
type NavigationSnapshot = { selected: CatalogEntry; activeCatalog: string | null; view: "menu" | "catalog" | "search"; category: string; query: string; slotFilter: string; cardTypeFilter: string; gemTypeFilter: string; equipmentTypeFilter: string };

const themes: Record<string, Theme> = {
  m: { label: "BMW M", background: "#050505", surface: "#1a1a1a", accent: "#ffffff", stripe: ["#0066b1", "#1c69d4", "#e22718"] },
  forest: { label: "Forest", background: "#101811", surface: "#1b291c", accent: "#b6e96b", stripe: ["#69d9a0", "#3eaf7c", "#d6e65a"] },
  midnight: { label: "Midnight", background: "#0b1020", surface: "#161d35", accent: "#91a4ff", stripe: ["#55c4ff", "#7478ff", "#d783ff"] },
  ember: { label: "Ember", background: "#180d0a", surface: "#291612", accent: "#ffad72", stripe: ["#ffcc66", "#ff7c4d", "#d33d3d"] },
};
const defaultCustom: Theme = { label: "Custom", background: "#111111", surface: "#242424", accent: "#47d7c1", stripe: ["#47d7c1", "#4183ff", "#e75e74"] };

function distance(left: string, right: string) { const table = Array.from({ length: left.length + 1 }, (_, index) => [index]); for (let column = 1; column <= right.length; column += 1) table[0][column] = column; for (let row = 1; row <= left.length; row += 1) for (let column = 1; column <= right.length; column += 1) table[row][column] = left[row - 1] === right[column - 1] ? table[row - 1][column - 1] : 1 + Math.min(table[row - 1][column], table[row][column - 1], table[row - 1][column - 1]); return table[left.length][right.length]; }
function search(entries: CatalogEntry[], rawQuery: string, category: string): SearchResult[] { const typeFilters = [...rawQuery.matchAll(/type:([\w-]+)/gi)].map((match) => normalize(match[1])); const exactPhrases = [...rawQuery.matchAll(/"([^"]+)"/g)].map((match) => normalize(match[1])); const terms = rawQuery.replace(/type:[\w-]+/gi, "").replace(/"[^"]+"/g, "").trim().split(/\s+/).filter(Boolean).map(normalize); return entries.map((entry): SearchResult | null => { if ((category !== "All" && entry.kind !== category) || (typeFilters.length > 0 && !typeFilters.includes(normalize(entry.kind)))) return null; const name = normalize(entry.name), aliases = normalize(entry.aliases ?? ""), nameWords = `${name} ${aliases}`.split(/[^a-z0-9]+/).filter(Boolean); const searchable = [entry.name, entry.aliases ?? "", entry.kind, entry.subtitle, entry.summary, ...entry.tags, ...entry.fields.flatMap((field) => [field.label, field.value])].map(normalize); let score = 0, reason = ""; for (const term of [...exactPhrases, ...terms]) { if (!searchable.some((value) => value.includes(term))) { const closest = Math.min(...nameWords.map((word) => distance(term, word))); if (term.length < 4 || closest > 2) return null; score += 25; reason ||= "Similar name"; } else if (name === term || aliases === term) { score += 100; reason ||= "Exact name"; } else if (name.startsWith(term) || aliases.startsWith(term)) { score += 70; reason ||= "Name starts with search"; } else if (name.includes(term) || aliases.includes(term)) { score += 55; reason ||= "Name match"; } else { score += 20; reason ||= "Matches details"; } } return { entry, score, reason }; }).filter((result): result is SearchResult => result !== null).sort((left, right) => right.score - left.score || left.entry.name.localeCompare(right.entry.name)); }

function LinkedFieldValue({ value, label, resolve, onNavigate }: { value: string; label: string; resolve: (line: string, label: string) => LinkMatch | null; onNavigate: (entry: CatalogEntry) => void }) {
  return <>{value.split("\n").map((line, index) => { const match = resolve(line, label); return <span className="detail-line" key={`${line}:${index}`}>{match ? <>{line.slice(0, match.start)}<button className="catalog-link" type="button" onClick={() => onNavigate(match.entry)}>{line.slice(match.start, match.start + match.length)}</button>{line.slice(match.start + match.length)}</> : line}{index < value.split("\n").length - 1 && <br />}</span>; })}</>;
}

function App() {
  const [query, setQuery] = useState(""); const [catalog, setCatalog] = useState<CatalogEntry[]>([]); const [selected, setSelected] = useState<CatalogEntry | null>(null); const [pinnedEntry, setPinnedEntry] = useState<CatalogEntry | null>(null); const [activeCatalog, setActiveCatalog] = useState<string | null>(null); const [view, setView] = useState<"menu" | "catalog" | "search">("menu"); const [category, setCategory] = useState("All"); const [slotFilter, setSlotFilter] = useState("All"); const [cardTypeFilter, setCardTypeFilter] = useState("All"); const [gemTypeFilter, setGemTypeFilter] = useState("All"); const [equipmentTypeFilter, setEquipmentTypeFilter] = useState("All"); const [language, setLanguage] = useState<"en" | "th">("en"); const [settingsOpen, setSettingsOpen] = useState(false); const [highlight, setHighlight] = useState(0); const [status, setStatus] = useState("Syncing database…"); const [loading, setLoading] = useState(true); const [motionEnabled, setMotionEnabled] = useState(true); const [themeName, setThemeName] = useState("m"); const [customTheme, setCustomTheme] = useState<Theme>(defaultCustom); const [history, setHistory] = useState<NavigationSnapshot[]>([]);
  const searchInput = useRef<HTMLInputElement>(null); const detailCard = useRef<HTMLElement>(null);

  const refreshCatalog = useCallback(async (showLoading = false) => { if (showLoading) { setLoading(true); setStatus("Syncing database…"); } try { const response = await invoke<CatalogResponse>("load_catalog"); setCatalog(response.entries); setStatus(`${response.source === "live" ? "Live" : "Cached"} database · ${response.entries.length} records`); if (response.source === "live") setLoading(false); } catch { setStatus("No verified database available"); } }, []);
  useEffect(() => { searchInput.current?.focus(); void refreshCatalog(true); const saved = localStorage.getItem("spiritvale-theme"); if (saved) { try { const preference = JSON.parse(saved); setThemeName(preference.name ?? "m"); if (preference.custom) setCustomTheme(preference.custom); if (typeof preference.motion === "boolean") setMotionEnabled(preference.motion); } catch { /* ignore corrupt local preference */ } } }, [refreshCatalog]);
  useEffect(() => localStorage.setItem("spiritvale-theme", JSON.stringify({ name: themeName, custom: customTheme, motion: motionEnabled })), [themeName, customTheme, motionEnabled]);
  const activeTheme = themeName === "custom" ? customTheme : themes[themeName];
  const themeStyle = { "--canvas": activeTheme.background, "--surface": activeTheme.surface, "--accent": activeTheme.accent, "--stripe-a": activeTheme.stripe[0], "--stripe-b": activeTheme.stripe[1], "--stripe-c": activeTheme.stripe[2] } as CSSProperties;
  const searchResults = useMemo(() => search(catalog, query, category), [catalog, query, category]); const showingMenu = view === "menu"; const visibleResults = view === "catalog" && activeCatalog ? searchResults.filter((result) => result.entry.kind === activeCatalog) : searchResults; const equipmentTypes = useMemo(() => [...new Set(catalog.filter((entry) => entry.kind === "Equipment").map((entry) => entry.subtitle).filter((type) => type && type !== "Equipment"))].sort(), [catalog]); const filterCatalog = activeCatalog ?? (category === "All" ? null : category); const filteredResults = useMemo(() => visibleResults.filter(({ entry }) => { if (filterCatalog === "Cards") return (slotFilter === "All" || entry.subtitle === slotFilter) && (cardTypeFilter === "All" || taggedType(entry, "Normal") === cardTypeFilter); if (filterCatalog === "Gems") return gemTypeFilter === "All" || taggedType(entry, "Skill") === gemTypeFilter; if (filterCatalog === "Equipment") return equipmentTypeFilter === "All" || entry.subtitle === equipmentTypeFilter; return true; }), [visibleResults, filterCatalog, slotFilter, cardTypeFilter, gemTypeFilter, equipmentTypeFilter]);
  const linkCandidates = useMemo<LinkCandidate[]>(() => catalog.flatMap((entry) => [entry.name, entry.aliases ?? ""].filter(Boolean).map((key) => ({ entry, key }))).sort((left, right) => right.key.length - left.key.length), [catalog]);
  const resolveLink = useCallback((line: string, label: string): LinkMatch | null => { const normalizedLine = normalize(line); const preferredKind = label === "Dropped by" || label === "Monsters" ? "Monsters" : label === "Locations" ? "Maps" : ""; const candidates = linkCandidates.filter(({ key }) => normalizedLine.includes(normalize(key))); const candidate = candidates.sort((left, right) => { const score = ({ entry, key }: LinkCandidate) => (normalize(key) === normalize(entry.name) ? 1000 : 0) + (entry.kind === preferredKind ? 100 : 0) + key.length; return score(right) - score(left); })[0]; if (!candidate) return null; const start = normalizedLine.indexOf(normalize(candidate.key)); return { entry: candidate.entry, start, length: candidate.key.length }; }, [linkCandidates]);
  useEffect(() => setHighlight(0), [query, category, activeCatalog, view, slotFilter, cardTypeFilter, gemTypeFilter, equipmentTypeFilter]); useEffect(() => { detailCard.current?.scrollTo({ top: 0, behavior: motionEnabled ? "smooth" : "auto" }); window.scrollTo({ top: 0, behavior: motionEnabled ? "smooth" : "auto" }); }, [selected, motionEnabled]);

  const resetCatalogFilters = () => { setSlotFilter("All"); setCardTypeFilter("All"); setGemTypeFilter("All"); setEquipmentTypeFilter("All"); };
  const mainMenu = () => { setView("menu"); setActiveCatalog(null); setCategory("All"); setQuery(""); setSelected(null); setHistory([]); resetCatalogFilters(); };
  const selectFromList = (entry: CatalogEntry) => { setSelected(entry); setHistory([]); };
  const navigateToLinked = (entry: CatalogEntry) => { if (selected?.id === entry.id) return; if (selected) setHistory((current) => [...current, { selected, activeCatalog, view, category, query, slotFilter, cardTypeFilter, gemTypeFilter, equipmentTypeFilter }]); setSelected(entry); setView("catalog"); setActiveCatalog(entry.kind); setCategory("All"); setQuery(""); resetCatalogFilters(); };
  const navigateBack = () => { const previous = history[history.length - 1]; if (!previous) return; setHistory((current) => current.slice(0, -1)); setSelected(previous.selected); setActiveCatalog(previous.activeCatalog); setView(previous.view); setCategory(previous.category); setQuery(previous.query); setSlotFilter(previous.slotFilter); setCardTypeFilter(previous.cardTypeFilter); setGemTypeFilter(previous.gemTypeFilter); setEquipmentTypeFilter(previous.equipmentTypeFilter); };
  const handleKeys = (event: KeyboardEvent<HTMLInputElement>) => { if (!filteredResults.length) return; if (event.key === "ArrowDown") { event.preventDefault(); setHighlight((current) => Math.min(current + 1, filteredResults.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setHighlight((current) => Math.max(current - 1, 0)); } else if (event.key === "Enter") { event.preventDefault(); selectFromList(filteredResults[highlight].entry); } };
  const beginDrag = (event: MouseEvent<HTMLElement>) => { if (!(event.target as HTMLElement).closest("button,input,select,label")) void invoke("begin_drag"); }; const isPinned = pinnedEntry?.id === selected?.id; const applyResolution = (width: number, height: number) => void invoke("set_window_size_preset", { width, height }); const updateCustom = (field: "background" | "surface" | "accent", value: string) => { setThemeName("custom"); setCustomTheme((current) => ({ ...current, [field]: value })); };

  return <main className={`overlay-shell ${motionEnabled ? "motion-on" : "motion-off"}`} style={themeStyle}>
    {loading && <section className="launch-loader" role="status"><span className="loader-sigil">✦</span><strong>SPIRITVALE</strong><p>{status}</p><i /></section>}
    <div className="sticky-chrome"><header className="masthead" onMouseDown={beginDrag}><div className="brand" data-tauri-drag-region><span className="sigil">✦</span><div><strong>SPIRITVALE</strong><small>{language === "en" ? "SpiritVale field guide" : "คู่มือ SpiritVale"}</small></div></div><div className="header-actions"><button className="language" aria-label="Change language" onClick={() => setLanguage(language === "en" ? "th" : "en")}>{language === "en" ? "ไทย" : "EN"}</button><button className="icon-button" aria-label="Minimize overlay" onClick={() => void invoke("minimize_overlay")}>−</button><button className="icon-button" aria-label="Settings" onClick={() => setSettingsOpen((open) => !open)}>⚙</button><button className="icon-button" aria-label="Close overlay" onClick={() => void invoke("close_overlay")}>×</button></div></header>
      <section className="search-zone"><span className="search-mark">⌕</span><input ref={searchInput} value={query} onKeyDown={handleKeys} onChange={(event) => { const next = event.target.value; setQuery(next); if (next.trim()) setView("search"); else mainMenu(); }} placeholder={language === "en" ? "Search names, stats, drops, crafting…" : "ค้นหาชื่อ ค่าสถานะ ดรอป การสร้าง…"} /><select className="search-filter" value={category} onChange={(event) => { const next = event.target.value; resetCatalogFilters(); setCategory(next); setActiveCatalog(null); if (next === "All" && !query.trim()) mainMenu(); else setView("search"); }} aria-label="Category filter"><option>All</option>{catalogs.map((item) => <option key={item}>{item}</option>)}</select></section>
      {filterCatalog === "Cards" && <section className="catalog-filters"><label>Slot<select value={slotFilter} onChange={(event) => setSlotFilter(event.target.value)}><option>All</option>{cardSlots.map((type) => <option key={type}>{type}</option>)}</select></label><label>Type<select value={cardTypeFilter} onChange={(event) => setCardTypeFilter(event.target.value)}><option>All</option><option>Boss</option><option>Normal</option></select></label></section>}
      {filterCatalog === "Gems" && <section className="catalog-filters"><label>Type<select value={gemTypeFilter} onChange={(event) => setGemTypeFilter(event.target.value)}><option>All</option><option>Boss</option><option>Skill</option></select></label></section>}
      {filterCatalog === "Equipment" && <section className="catalog-filters"><label>Type<select value={equipmentTypeFilter} onChange={(event) => setEquipmentTypeFilter(event.target.value)}><option>All</option>{equipmentTypes.map((type) => <option key={type}>{type}</option>)}</select></label></section>}
    </div>
    {settingsOpen && <aside className="settings-panel"><div className="settings-title"><span>SETTINGS</span><button aria-label="Close settings" onClick={() => setSettingsOpen(false)}>×</button></div><p>THEME PRESETS</p><div className="theme-grid">{Object.entries(themes).map(([key, theme]) => <button key={key} className={themeName === key ? "active" : ""} onClick={() => setThemeName(key)}><i style={{ background: `linear-gradient(90deg, ${theme.stripe.join(",")})` }} />{theme.label}</button>)}</div><p>CUSTOM THEME</p><div className="custom-colors">{(["background", "surface", "accent"] as const).map((field) => <label key={field}>{field}<input type="color" value={customTheme[field]} onChange={(event) => updateCustom(field, event.target.value)} /></label>)}</div><p>WINDOW RESOLUTION</p><div className="resolution-grid">{resolutions.map(([width, height, label]) => <button key={label} onClick={() => applyResolution(width, height)}>{label}<small>{width}×{height}</small></button>)}<button className="remember-size" onClick={() => void invoke("remember_current_window_size")}>Remember current size</button></div><p>MOTION</p><button className={`motion-toggle ${motionEnabled ? "is-on" : ""}`} onClick={() => setMotionEnabled((enabled) => !enabled)}><span>{motionEnabled ? "ON" : "OFF"}</span>Animations {motionEnabled ? "enabled" : "disabled"}</button><button className="refresh-settings" onClick={() => void refreshCatalog(true)}>Refresh database</button></aside>}
    {pinnedEntry && <section className="pinned-panel"><span>PINNED</span>{pinnedEntry.imageUrl && <img src={pinnedEntry.imageUrl} alt="" />}<strong>{pinnedEntry.name}</strong><small>{pinnedEntry.subtitle}</small><button onClick={() => navigateToLinked(pinnedEntry)}>Open</button><button onClick={() => setPinnedEntry(null)}>Unpin</button></section>}
    <section className="content-grid"><aside key={`${view}:${query}:${category}:${slotFilter}:${cardTypeFilter}:${gemTypeFilter}:${equipmentTypeFilter}`} className="result-list">{showingMenu ? catalogs.map((item, index) => <button className="catalog-button" style={{ "--i": index, "--catalog-color": catalogColors[item] } as CSSProperties} key={item} onClick={() => { resetCatalogFilters(); setActiveCatalog(item); setView("catalog"); }}><span className={`kind ${catalogClass(item)}`}>{item}</span><span className="result-copy"><strong>{item}</strong><small>{catalog.filter((entry) => entry.kind === item).length} records</small></span><span className="arrow">›</span></button>) : <><button className="back-button" onClick={mainMenu}>← {language === "en" ? "Back to main menu" : "กลับเมนูหลัก"}</button>{filteredResults.map((result, index) => <button style={{ "--i": index } as CSSProperties} key={`${result.entry.id}:${index}`} className={`result ${selected?.id === result.entry.id || index === highlight ? "active" : ""}`} onMouseEnter={() => setHighlight(index)} onClick={() => selectFromList(result.entry)}><span className={`kind ${catalogClass(result.entry.kind)}`}>{result.entry.kind}</span><span className="result-copy"><strong>{result.entry.name}</strong><small>{result.reason} · {result.entry.subtitle}</small></span></button>)}</>}{!showingMenu && filteredResults.length === 0 && <p className="empty-results">No matching records.</p>}</aside>{selected ? <article key={selected.id} ref={detailCard} className="detail-card detail-enter"><div className="item-heading">{selected.imageUrl && <img className="item-image" src={selected.imageUrl} alt="" />}<div><h1>{selected.name}</h1><p className="subtitle">{selected.subtitle}</p></div></div><p className="summary">{selected.summary}</p><dl>{selected.fields.map((field) => <div key={field.label}><dt>{field.label}</dt><dd><LinkedFieldValue value={field.value} label={field.label} resolve={resolveLink} onNavigate={navigateToLinked} /></dd></div>)}</dl><div className="detail-actions">{history.length > 0 && <button className="detail-back" onClick={navigateBack}>← Back to {history[history.length - 1]?.selected.name}</button>}<button className={`pin-button ${isPinned ? "is-pinned" : ""}`} onClick={() => setPinnedEntry(isPinned ? null : selected)}>{isPinned ? "✦ Unpin details" : "◇ Pin details"}</button><button className="source-button" onClick={() => openUrl(selected.sourceUrl)}>View source ↗</button></div></article> : <article className="detail-card loading-card"><p>Choose a catalog or search the database.</p></article>}</section>
    <footer><span className="pulse" />{status}<span className="divider">·</span><span>v1.1.1</span><button className="sync-button" onClick={() => void refreshCatalog(true)}>Refresh</button></footer>
  </main>;
}
export default App;